### ISSUE TITLE
List Transfer Method Configs throws a parsing exception

### ISSUE THREAD

**Issue by blockclin-mike** [hyperwallet/java-sdk#23]
**The method call**:
HyperwalletList<HyperwalletTransferMethodConfiguration> trms = hw.listTransferMethodConfigurations(user.getToken());

**Produces**:
Exception in thread "main" com.hyperwallet.clientsdk.HyperwalletException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.hyperwallet.clientsdk.model.HyperwalletTransferMethodConfiguration$Field$DataType from String value 'PHONE': value not one of declared Enum instance names: [TEXT, SELECTION, BOOLEAN, NUMBER]
 at [Source: java.io.StringReader@71e693fa; line: 303, column: 29] (through reference chain: com.hyperwallet.clientsdk.model.HyperwalletList["data"]->java.util.ArrayList[0]->com.hyperwallet.clientsdk.model.HyperwalletTransferMethodConfiguration["fields"]->java.util.ArrayList[7]->com.hyperwallet.clientsdk.model.Field["dataType"])
	at com.hyperwallet.clientsdk.util.HyperwalletJsonUtil.fromJson(HyperwalletJsonUtil.java:43)
	at com.hyperwallet.clientsdk.util.HyperwalletApiClient.convert(HyperwalletApiClient.java:165)
	at com.hyperwallet.clientsdk.util.HyperwalletApiClient.processResponse(HyperwalletApiClient.java:117)
	at com.hyperwallet.clientsdk.util.HyperwalletApiClient.get(HyperwalletApiClient.java:55)
	at com.hyperwallet.clientsdk.Hyperwallet.listTransferMethodConfigurations(Hyperwallet.java:1511)
	at com.hyperwallet.clientsdk.Hyperwallet.listTransferMethodConfigurations(Hyperwallet.java:1496)

**Comment by wmews-hw** [comment]
@blockclin-mike sorry for a late response. Is it still a problem?

**Comment by blockclin-mike** [comment]
I don't think so. I would actually have to go back through some old notes
to remember what I was asking about. I have gotten our integration working
w/ the HW servers in UAT and are readying to go live, so I think this can
just be closed out. If you need more info on the issue I'll try to figure
out if I worked around or figured out it was and RTFM issue.


Best Regards,

Mike Lewis
VP and Co-founder
BlockClinical, Inc.

**Comment by wmews-hw** [comment]
Thanks @blockclin-mike for replying. 
I'll close it because we haven't seen this issue in the past months as well.
